apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mydecks-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: mydecks.jlnshen.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mydecks
            port:
              number: 3000
